image: 'gradle:8.7.0'
pipelines:
  branches:
    main:
      - parallel:
          - step:
              name: Build and Test
              caches:
              - gradle
              script:
              - gradle build
              - pipe: 'atlassian/bitbucket-upload-file:0.7.1'
                variables:
                  BITBUCKET_ACCESS_TOKEN: $BITBUCKET_ACCESS_TOKEN
                  FILENAME: build/distributions/*.zip
              after-script:
              - pipe: 'atlassian/checkstyle-report:0.3.0'
      - step:
          name: Security Scan
          script:
            - pipe: 'atlassian/git-secrets-scan:0.5.1'
    develop:
      - parallel:
        - step:
            name: Build and Test
            caches:
            - gradle
            script:
            - gradle build
            after-script:
            - pipe: 'atlassian/checkstyle-report:0.3.0'
      - step:
          name: Security Scan
          script:
            - pipe: 'atlassian/git-secrets-scan:0.5.1'